# actionlint configuration
# See: https://github.com/rhymond/actionlint

# Enable all rules
self-hosted-runner: true
pyflakes: true
shellcheck: true

# Configure specific rules
ignore:
  # Allow using ${{ }} in shell scripts when necessary
  - 'SC2016'
  # Allow using variables in shell conditionals  
  - 'SC2086'