---
extends: default

rules:
  line-length:
    max: 120
  trailing-spaces: enable
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  indentation:
    spaces: 2
  document-start: disable
  truthy: disable